export function createDemoAnalysis() {
  return {
    cameraActive: false,
    personDetected: false,
    faceDetected: false,
    bodyVisible: "none",
    exercise: "Squat",
    set: 2,
    targetReps: 15,
    completedReps: 12,
    correctReps: 9,
    incorrectReps: 3,
    formScore: 82,
    confidence: 0.91,
    durationSeconds: 154,
    averageRepTimeSeconds: 3.8,
    caloriesEstimate: 18,
    scores: {
      balance: 88,
      rangeOfMotion: 76,
      speedControl: 84,
      posture: 79,
    },
    angles: {
      leftKnee: 94,
      rightKnee: 96,
      leftHip: 104,
      rightHip: 101,
      leftElbow: null,
      rightElbow: null,
      shoulder: 89,
      torso: 92,
    },
    mistakes: [
      {
        type: "knees_caving_inward",
        label: "Knees caving inward",
        severity: "medium",
        count: 2,
        suggestion: "Push your knees outward and align them with your toes.",
      },
      {
        type: "back_not_straight",
        label: "Back not straight",
        severity: "high",
        count: 1,
        suggestion: "Keep your chest up and spine neutral.",
      },
    ],
    activeSuggestion: "Push your knees outward.",
    repResults: [
      { repNumber: 1, score: 91, status: "excellent", mistake: null, durationSeconds: 3.2, correct: true },
      { repNumber: 2, score: 88, status: "good", mistake: null, durationSeconds: 3.5, correct: true },
      { repNumber: 3, score: 64, status: "needs_work", mistake: "Knees caving inward", durationSeconds: 2.8, correct: false },
      { repNumber: 4, score: 72, status: "needs_work", mistake: "Not reaching full depth", durationSeconds: 3.0, correct: false },
      { repNumber: 5, score: 84, status: "good", mistake: null, durationSeconds: 3.4, correct: true },
    ],
    source: "demo",
    timestamp: new Date().toISOString(),
    robotPose: { x: 0.4, y: 0.1, yaw: 0.2 },
    rawPayload: { mode: "demo" },
  };
}
